# Site settings
title: "XinlongWu's Resume"
description: "It is a profile page for RMIT University Student XinlongWu"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Xinlong Wu"
resume_title:                   "Personal Info"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "s3860954@student.rmit.edu.au"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0477 124 542"
resume_contact_address:         "502 Swanston Street, Carlton, VIC"

resume_header_contact_info:     "None"
display_header_contact_info:    "false"

resume_header_intro: "<p>This is Xinlong Wu(s3860954), a 3rd year Bachelor of Information Technology student at RMIT University. I am from Inner Mongolia, China, which is a place with a strong animal husbandry industry as Australia. I have currently obtained my undergraduate degree in Computer Science from Beijing Normal University, Zhuhai, China. Due to the exchange between the two schools, I am currently enrolled in RMIT's Bachelor of Information Technology. This semester is my last semester at RMIT and I will graduate this year if all goes well.</p><p>Actually, I always maintain a sort of interest/curiosity in anything/activity if it's interesting, so just invite me if there's something fun to do！</p><p>Besides that, my other biggest interest is IT & CS. I have a strong interest in how computers get up and running. I am currently an intern at a company focused on contributing to the Clang/LLVM open source compiler. Before that I also tried to implement a simple operating system, and I am currently designing a CPU by myself. They are all in my Github Repo.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_interest:        true
resume_section_ideal_job:       true
resume_section_projects:        true
resume_section_project_idea:    true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Xinlong-Wu"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://www.wulongxin.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
